version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      nx-packages:
        patterns:
          - "nx"
          - "@nx/*"

      dev-dependencies:
        dependency-type: "development"
        exclude-patterns:
          - "nx"
          - "@nx/*"
        update-types:
          - "minor"
          - "patch"

      prod-dependencies:
        dependency-type: "production"
        exclude-patterns:
          - "nx"
          - "@nx/*"
        update-types:
          - "minor"
          - "patch"
